### ISSUE TITLE
Location Details

### ISSUE THREAD

**Issue by MikeRogers0** [phpsurrey/phpsurrey.uk#1]
A page on the current site with a nice Google map of how to find to venue. Perhaps even parking & travel information.

**Comment by michaelcullum** [comment]
![20150721_134554](https://cloud.githubusercontent.com/assets/211740/8832423/e64e2c64-30a0-11e5-8733-a19414709d98.jpg)

**Comment by michaelcullum** [comment]
Trains - From Guildford station it is a 10 minute walk. Turn right out of the station (towards bridge house). At bridge house turn left towards the YMCA. When you get to the traffic lights cross over and turn right and follow that road around to the left (to the left of the taxi rank) until you are on north street (Looks like a high street). Walk up north street (past Argos and HSBC) until you get to RBS (opposite Betfred) then turn left and the guildford institute is just down that lane (Ward Street) on the left.
