### ISSUE TITLE
Structure

### ISSUE THREAD

**Issue by michaelcullum** [phpsurrey/phpsurrey.uk#7]
I'd like to switch this over to a proper php site (Silex & Twig) with a bootstrap template or something.

**Comment by MikeRogers0** [comment]
Are we going to stick with GitHub page hosting? [Jekyll](https://help.github.com/articles/using-jekyll-with-pages/) seems to be the preferred method if we do.

Also +1 on using a bootstrap based theme.

**Comment by michaelcullum** [comment]
I think PHP would be easier if we want to go the route of #5 like php dorset's system (which is OS and available as a lib).

**Comment by MikeRogers0** [comment]
Silex with twig looks pretty nice, I'll try and get the current site plus a few simple pages done ASAP :)

**Comment by michaelcullum** [comment]
Awesome. Use the lib in phodorset's website repo, it looks pretty neat.

**Comment by MikeRogers0** [comment]
Where are you looking? ( https://github.com/PHPDorset/phpdorset.github.io - I can't see the /lib folder )

**Comment by michaelcullum** [comment]
https://github.com/PHPDorset/phpdorset.github.io/tree/master/app/src/PhpDorset/Presentation

The lib is `PhpDorset\Presentation` I guess

**Comment by MikeRogers0** [comment]
Are you ok if I add that it once I get the initial structure (Upcoming events + location page also) together?

**Comment by michaelcullum** [comment]
Sure. I don't mind adding the talks stuff myself if you'd rather just do the rest?

**Comment by MikeRogers0** [comment]
Sounds good (Wanna talk on Skype to iron on who does what? / Make sure we are on the same approach). 

I've started on getting the current site running on [silex on my own fork](https://github.com/MikeRogers0/phpsurrey.github.io/tree/silex-build), I'll try to get the design using bootstrap by Sunday :)
